services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      PGPORT: ${DATABASE_PORT}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  api:
    build: .
    restart: always
    env_file: .env

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    networks:
      - network

volumes:
  postgres-data:


networks:
  network:
